name: UI tests (Selenium + pytest)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Selenium with Python Tutorials/requirements.txt"

      - name: Run tests (JUnit report)
        run: |
          mkdir -p reports
          python -m pytest -v --junitxml=reports/junit.xml

      - name: Upload test report (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml
